### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by haxxus** [Da532/Clear#4]
Hello , I'm getting this error , I tried the token on another bot and it works so i'm not sure what this is 

```
root@vultr:/home/Clear# python3.6 bot.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 36, in <module>
    bot.run(token, bot=False)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fa081d00a90>

```

any help ? thanks.

**Comment by KingDGrizzle** [comment]
`discord.errors.LoginFailure: Improper token has been passed.`

Seems like your token is wrong.
